font_family JetBrainsMonoNL NF SemiBold
bold_font   JetBrainsMonoNL NF ExtraBold


background        #232323
foreground        #d9d9d9
selection_background #5e5e5e
selection_foreground #d9d9d9
cursor            #7c5fc0
cursor_text_color #232323

active_border_color   #7c5fc0
inactive_border_color #5e4a93
bell_border_color     #c2565a

# Tab bar colors
active_tab_background   #d9d9d9
active_tab_foreground   #232323
inactive_tab_background #232323
inactive_tab_foreground #d9d9d9
tab_bar_background      #232323

# Marks (used for search, etc.)
mark1_background #7c5fc0
mark1_foreground #232323
mark2_background #5e4a93
mark2_foreground #232323
mark3_background #5ca7a7
mark3_foreground #232323

# Standard colors
# color0  #232323
# color1  #c2565a
# color2  #5ca77c
# color3  #c2a85c
# color4  #5c7cc2
# color5  #7c5fc0
# color6  #5ca7a7
# color7  #d9d9d9
color0 #232323
color1 #BF4044
color2 #44BF40
color3 #CFCF40
color4 #4044BF
color5 #7640BF
color6 #40BFB5
color7 #d9d9d9

# Bright colors
color8  #232323
color9  #E85C5F
color10 #5EDD5A
color11 #E8E85A
color12 #6060FF
color13 #7640BF
color14 #7640BF
color15 #d9d9d9