font_family JetBrainsMonoNL NF SemiBold
bold_font   JetBrainsMonoNL NF ExtraBold

# Background
background #232323
foreground #d9d9d9

# Cursor
cursor #d9d9d9
cursor_text_color #232323

# Selection
selection_background #5e5e5e
selection_foreground #d9d9d9

# URL underline
url_color #82a5f3

# Windows border
active_border_color #82a5f3
inactive_border_color #444444
bell_border_color #f48084

# Tab bar
tab_bar_background #202020
tab_bar_margin_color #202020
active_tab_background #282828
active_tab_foreground #f5f5f5
inactive_tab_background #1a1a1a
inactive_tab_foreground #d9d9d9
tab_separator_color #444444

# Standard colors
color0 #121212
color1 #c2565a
color2 #5ca77c
color3 #c2a85c
color4 #5c7cc2
color5 #7c5fc0
color6 #5ca7a7
color7 #e5e5e5

# Bright colors
color8 #5e5e5e
color9 #f48084
color10 #95dfb5
color11 #f3d682
color12 #82a5f3
color13 #a484f0
color14 #95dfdf
color15 #FFFFFF
